# Generated by Django 5.0.2 on 2025-05-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_topic_topicprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='topics', to='core.video'),
        ),
    ]
